Repository jalantechnologies/react-native-template, pull requests merged in 2025-06, with the labels that each got.

#149 feat: enhance Change API URL button
  src/screens/auth/auth-layout.tsx
  src/screens/auth/change-api-url/change-api-url.tsx
  src/screens/auth/phone-auth/phone-auth-form.tsx
Labels: boilerplate

#168 Use npm registry directly for Yarn dependencies
  .yarnrc
  package.json
  yarn.lock
Labels: chore

#165 Feat: Add support for deploying on Android (Preview)
  .github/CI_README.md
  .github/actions/setup-fastlane/action.yml
  .github/workflows/cleanup_firebase_on_pr_close.yml
  .github/workflows/preview_on_pr_update.yml
  .github/workflows/production_on_push.yml
  android/app/build.gradle
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  android/fastlane/scripts/firebase_distribution_service.rb
  android/fastlane/scripts/firebase_pr_cleanup.rb
  android/fastlane/scripts/firebase_pr_deploy.rb
Labels: devops
